### ISSUE TITLE
 Creating accounts (3/4)Error: Request failed with status code 403

### ISSUE THREAD

**Issue by wangxili11** [JunkMeal/duolingo-plus#5]
Hello how to deal with this problem of 403?

Creating accounts (3/4)Error: Request failed with status code 403
    at createError (D:\Downloads\duolingo-super\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\Downloads\duolingo-super\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\Downloads\duolingo-super\node_modules\axios\lib\adapters\http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',

**Comment by Lioness100** [comment]
Usually just rerunning the command works for me.

**Comment by JunkMeal** [comment]
Ill look into it once I am home, Ill add better error messages and error handling

**Comment by wangxili11** [comment]
Okay thanks, I restarted the run and it still didn't work

**Comment by wangxili11** [comment]
> 我回家后会调查它，我会添加更好的错误消息和错误处理

Hello! Is your side working properly?

**Comment by JunkMeal** [comment]
> > 我回家后会调查它，我会添加更好的错误消息和错误处理
> 
> Hello! Is your side working properly?

No, it is not. I am trying to fix it right now.

**Comment by JunkMeal** [comment]
Should I just make it use the browser (puppeteer) ?

**Comment by JunkMeal** [comment]
Captcha bypass doesnt work ill make it use a browser

**Comment by wangxili11** [comment]
> 验证码绕过不起作用使其使用浏览器

Is there any way to solve it?

**Comment by JunkMeal** [comment]
> > 验证码绕过不起作用使其使用浏览器
> 
> Is there any way to solve it?

You would need to use a browser (puppeteer) to do the registering.
If anyone does that i would merge the pull request
